pluginManagement {
    repositories {
        mavenCentral()
        google()
        gradlePluginPortal()
    }
}

include(':compose')
include(':view')

// This allows us to simplify the dependency management across apps by using fixed versions via a version catalog.
dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            from(files("libs/pfa-core/libs.versions.toml"))
        }
    }
}
include ':model'
project(':model').projectDir = new File(rootDir, 'libs/pfa-core/model/')
// For view-based app
include ':ui-view'
project(':ui-view').projectDir = new File(rootDir, 'libs/pfa-core/ui-view/')
// For compose based app
include ':ui-compose'
project(':ui-compose').projectDir = new File(rootDir, 'libs/pfa-core/ui-compose/')
include ':backup-api'
project(':backup-api').projectDir = new File('libs/pfa-core/libs/privacy-friendly-backup-api/BackupAPI')